/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssssss;

import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Cristhian Elvis
 */
public class UNIVERSITARIO extends javax.swing.JFrame {
	
	CardLayout vista;
	/**
	 * Creates new form UNIVERSITARIO
	 */
	public UNIVERSITARIO() {
		super("UNIVERSIDAD PERUANA DEL ORIENTE");
		initComponents();
		vista = (CardLayout) Panel_VistaPrincipal.getLayout();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                g.drawImage(new ImageIcon("C:\\Users\\User\\Documents\\Bluethu\\Fondo3.jpg").getImage(), 0, 0, getWidth(), getHeight(), this);

                setOpaque(false);
                super.paint(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jTBt1 = new javax.swing.JToggleButton();
        jTBt2 = new javax.swing.JToggleButton();
        jTBd1 = new javax.swing.JToggleButton();
        jTBd2 = new javax.swing.JToggleButton();
        jTBe1 = new javax.swing.JToggleButton();
        jTBe2 = new javax.swing.JToggleButton();
        jTBt3 = new javax.swing.JToggleButton();
        jTBd3 = new javax.swing.JToggleButton();
        jTBe3 = new javax.swing.JToggleButton();
        Panel_VistaPrincipal = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                g.drawImage(new ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\SOFT taller\\UPO2.jpg").getImage(), 0, 0, getWidth(), getHeight(), this);

                setOpaque(false);
                super.paint(g);
            }
        };

        buttonGroup1.add(jTBd1);
        buttonGroup1.add(jTBd2);
        buttonGroup1.add(jTBd3);
        buttonGroup1.add(jTBt1);
        buttonGroup1.add(jTBt2);
        buttonGroup1.add(jTBt3);
        buttonGroup1.add(jTBe1);
        buttonGroup1.add(jTBe2);
        buttonGroup1.add(jTBe3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));
        setExtendedState(6);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU DEL SISTEMA");

        jTBt1.setText("REGISTRAR TRABAJADOR");
        jTBt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBt2.setText("ELIMINAR TRABAJADOR");
        jTBt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBd1.setText("AGREGAR DEPARTAMENTO");
        jTBd1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTBd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBd1ActionPerformed(evt);
            }
        });

        jTBd2.setText("ELIMINAR DEPARTAMENTO");
        jTBd2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBe1.setText("AGREGAR ESTUDIANTE");
        jTBe1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBe2.setText("ELIMINAR ESTUDIANTE");
        jTBe2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBt3.setText("MOSTRAR TRABAJADORES");
        jTBt3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBd3.setText("MOSTRAR DEPARTAMENTOS");
        jTBd3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTBe3.setText("MOSTRAR ESTUDIANTES");
        jTBe3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTBd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTBd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTBd3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTBt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTBt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTBt3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTBe3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTBe1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBe2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jTBd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBd3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jTBt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jTBe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBe2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBe3)
                .addGap(24, 24, 24))
        );

        Panel_VistaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_VistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_VistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBd1ActionPerformed
        // TODO add your handling code here:
		//Panel_VistaPrincipal.add(new AddDepartamento());
		Panel_VistaPrincipal.add(new AddDepartamento(),"addDepa");
		vista.show(Panel_VistaPrincipal, "addDepa");
		SwingUtilities.updateComponentTreeUI(this);
		repaint();
    }//GEN-LAST:event_jTBd1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UNIVERSITARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UNIVERSITARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UNIVERSITARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UNIVERSITARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UNIVERSITARIO().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_VistaPrincipal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jTBd1;
    private javax.swing.JToggleButton jTBd2;
    private javax.swing.JToggleButton jTBd3;
    private javax.swing.JToggleButton jTBe1;
    private javax.swing.JToggleButton jTBe2;
    private javax.swing.JToggleButton jTBe3;
    private javax.swing.JToggleButton jTBt1;
    private javax.swing.JToggleButton jTBt2;
    private javax.swing.JToggleButton jTBt3;
    // End of variables declaration//GEN-END:variables
}
